#ifndef ADDRESSBOOK_GLOBAL_H
#define ADDRESSBOOK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ADDRESSBOOK_LIBRARY)
#  define ADDRESSBOOKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ADDRESSBOOKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ADDRESSBOOK_GLOBAL_H
